name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & Run
        run: |
            docker-compose build && docker-compose up --abort-on-container-exit --exit-code-from pdfparser && docker-compose down
